### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by azrsh** [sorah-rbpkg/actions#3]
This time, I will do it manually, so I will leave a record in this issue.

**Comment by azrsh** [comment]
Created the v1.0.0 release. The v1.0.0 tag was also created at the same time.

- https://github.com/sorah-rbpkg/actions/releases/tag/v1.0.0

**Comment by azrsh** [comment]
Created v1.0 tag

```console
$ git tag -a v1.0 -m "Create v1.0 tag"
$ git push origin v1.0
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 180 bytes | 180.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
To ssh://github.com/sorah-rbpkg/actions.git
 * [new tag]         v1.0 -> v1.0
```

**Comment by azrsh** [comment]
Created v1 tag

```console
$ git tag -a v1 -m "Create v1 tag"
$ git push origin v1
Enumerating objects: 1, done.
Counting objects: 100% (1/1), done.
Writing objects: 100% (1/1), 178 bytes | 178.00 KiB/s, done.
Total 1 (delta 0), reused 0 (delta 0), pack-reused 0
To ssh://github.com/sorah-rbpkg/actions.git
 * [new tag]         v1 -> v1
```

**Comment by azrsh** [comment]
According to https://github.com/actions/toolkit/blob/main/docs/action-versioning.md#recommendations we should publish this action to GitHub Marketplace.
But I can't in @sorah-rbpkg organization. Could you please make it possible, @sorah?

<img width="769" alt="image" src="https://github.com/sorah-rbpkg/actions/assets/46126763/2d61e9cc-0c8e-4dbc-99a0-854e8b599324">

**Comment by sorah** [comment]
done

**Comment by azrsh** [comment]
Thank you @sorah !
Published to the GitHub Marketplace. All tasks completed.
